# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: elasticsearch
  tag: "1.5.2"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

extraEnv: []

service:
  type: ClusterIP
  port: 9200

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
