apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tutor.fullname" . }}-cms-workers
  labels:
    app.kubernetes.io/component: cms-workers
    {{- include "tutor.common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workers.cms.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: cms-workers
      {{- include "tutor.common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cms-workers
        {{- include "tutor.common.labels" . | nindent 8 }}
      annotations:
        checksum/tutor-config: {{ include (print $.Template.BasePath "/tutor-configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: tutor-config
          emptyDir: {}
      initContainers:
        {{- include "tutor.config.container" . | nindent 8 }}
      containers:
        - name: cms-workers
          image: "{{ .Values.DOCKER_IMAGE_OPENEDX }}"
          imagePullPolicy: {{ .Values.openedx.image.pullPolicy }}
          env:
            - name: SERVICE_VARIANT
              value: cms
            - name: SETTINGS
              value: tutor.production
            - name: C_FORCE_ROOT # run celery tasks as root #nofear
              value: "1"
          command: ["./manage.py", "cms", "celery", "worker", "--loglevel=info", "--hostname=edx.cms.core.default.%%h", "--maxtasksperchild=100"]
          volumeMounts:
            - name: tutor-config
              mountPath: /openedx/edx-platform/cms/envs/tutor/
              subPath: env/apps/openedx/settings/cms
            - name: tutor-config
              mountPath: /openedx/config/
              subPath: env/apps/openedx/config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
