apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutor.fullname" . }}-lms
  labels:
    app.kubernetes.io/component: lms
    {{- include "tutor.common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.lms.service.type }}
  ports:
    - name: http
      port: {{ .Values.lms.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/component: lms
    {{- include "tutor.common.matchLabels" . | nindent 4 }}
