apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tutor.fullname" . }}-migrate-lms
  labels:
    app.kubernetes.io/component: migrate-lms
    {{- include "tutor.common.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "tutor.fullname" . }}-migrate-lms
      labels:
        app.kubernetes.io/component: migrate-lms
        {{- include "tutor.common.labels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      initContainers:
        {{- include "tutor.config.container" . | nindent 8 }}
      containers:
        {{- include "tutor.openedx.migrate" (dict "Values" .Values "ServiceVariant" "lms") | nindent 8 }}
      volumes:
        - name: tutor-config
          emptyDir: {}
