apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app.kubernetes.io/component: mysql
    {{- include "tutor.common.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.MYSQL_ROOT_PASSWORD | b64enc | quote }}
