apiVersion: v1
kind: Service
metadata:
 name: {{ include "tutor.fullname" . }}-smtp
 labels:
    app.kubernetes.io/component: smtp
    {{- include "tutor.common.labels" . | nindent 4 }}
spec:
 type: ExternalName
 externalName: {{ .Values.SMTP_HOST }}
