{{- if .Values.generateSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mysql.name" . }}
    helm.sh/chart: {{ include "mysql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mysql-root-password: {{ .Values.rootPassword | b64enc | quote }}
{{- end -}}
